require:
  - rubocop-rspec
  - rubocop-performance
  - rubocop-md

AllCops:
  TargetRubyVersion: 2.7

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Metrics/ParameterLists:
  CountKeywordArgs: false

Style/WhileUntilModifier:
  Enabled: false

Naming/MethodParameterName:
  Exclude:
    - '**/*.md'
    - 'spec/**/*'

Style/MixinUsage:
  Exclude:
    - '**/*.md'

Lint/UnusedMethodArgument:
  Exclude:
    - '**/*.md'

Lint/UnusedBlockArgument:
  Exclude:
    - '**/*.md'

Style/CaseEquality:
  Exclude:
    - 'lib/flows/type/**/*'

Naming/RescuedExceptionsVariableName:
  PreferredName: err
