require:
  - rubocop-rspec
  - rubocop-performance
  - rubocop-md

AllCops:
  TargetRubyVersion: 2.6

LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Metrics/ParameterLists:
  CountKeywordArgs: false

Style/WhileUntilModifier:
  Enabled: false

Naming/UncommunicativeMethodParamName:
  Exclude:
    - '**/*.md'

Style/MixinUsage:
  Exclude:
    - '**/*.md'
