name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: 0 2 * * 1-5

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - 2.5.x
          - 2.6.x
          - 2.7.x
    steps:
      - uses: actions/checkout@v1
      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Install Bundler
        run: gem install bundler
      - name: Install Hunspell
        run: sudo apt-get install hunspell
      - name: Install Deps
        run: bundle install --jobs 4 --retry 3
      - name: Test
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: bundle exec rake
